### ISSUE TITLE
Uncaught TypeError: Cannot read property 'priority' of undefined

### ISSUE THREAD

**Issue by jody90** [atom/status-bar#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.79.0

### Stack Trace

Uncaught TypeError: Cannot read property 'priority' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/status-bar/lib/status-bar-view.js:60

TypeError: Cannot read property 'priority' of undefined
  at status-bar.StatusBarView.addLeftTile (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/status-bar-view.js:60:132)
  at updateStatusbar (/home/johannes/.atom/packages/jshint/index.js:130:13)
  at registerEvents (/home/johannes/.atom/packages/jshint/index.js:304:2)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -7:37.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:37.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:35.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 11x -7:19.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:11.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -7:10.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:10.7.0 tree-view:toggle (atom-text-editor.editor)
     -7:06.1.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -5:51.5.0 core:copy (atom-text-editor.editor.is-focused)
     -5:49.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:49.1.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -5:48.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:48 core:paste (atom-text-editor.editor.is-focused)
  3x -5:30.7.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -5:19.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/var/www/shop/",
    "disabledPackages": [
      "wrap-guide",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c"
    ],
    "themes": [
      "atom-dark-ui",
      "razor-atom-syntax-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sass-Syntax-Highlight, v0.1.1
ScssBundle, v0.5.0
atom-alignment, v0.12.1
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-wordpress-hooks, v0.2.0
color-picker, v2.0.13
color-tabs, v0.1.8
color-tabs-regex, v0.2.2
css-snippets, v0.9.0
csslint, v1.1.4
file-icons, v1.6.11
highlight-line, v0.11.0
indent-guide-improved, v1.4.3
javascript-snippets, v1.0.0
jshint, v1.8.1
jslint, v1.4.0
jsonlint, v1.1.2
language-SCSS, v0.4.0
line-diff-details, v1.1.3
linter, v1.8.1
linter-php, v1.0.5
minimap, v4.13.4
pigments, v0.18.0
razor-atom-syntax-theme, v2.2.3
react, v0.12.10
selection-highlight, v0.1.4
tab-control, v0.6.8
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Looks like `jshint` is causing this error - @jody90 can you try disabling the `jshint` package and see if that helps?

**Comment by sebashotte** [comment]
Hi, I just got this issue and my `jshint` is disable.

Thanks

**Comment by tyrsius** [comment]
I just got this issue and I don't have jshint installed

**Comment by 50Wliu** [comment]
@tyrsius can you please open a new issue on [atom/image-view](https://github.com/atom/image-view) for your exception?  Thanks.

Until there's evidence that status-bar is at fault here and not packages consuming status-bar, I'm going to close this issue.

**Comment by mikeerickson** [comment]
@50Wliu I dont have jsHint installed either and am receiving the error.

**Comment by 50Wliu** [comment]
@mikeerickson Please open a new issue and paste in the Notifications error.  Thanks!
