### ISSUE TITLE
Failed to activate the status-bar package

### ISSUE THREAD

**Issue by ButchAnton** [atom/status-bar#111]
I was updating the status-bar package and received the following error.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.2
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.80.0

### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (/Users/i831533/.atom/packages/status-bar/lib/main.coffee:22:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -1:28.2.0 core:select-all (atom-text-editor.editor.is-focused)
  2x -1:23.1.0 copy-as-rtf:copy (atom-text-editor.editor.is-focused)
     -0:27.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai-dark.theme-atom-dark-extended-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-extended-ui",
      "monokai-dark"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-extended-ui, v0.23.2
copy-as-rtf, v0.8.1
cucumber, v0.5.0
linter, v1.10.0
monokai-dark, v1.3.0
package-sync, v0.2.0
status-bar, v0.80.0
terminal-status, v1.6.8
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please remove the `status-bar` package by executing `apm uninstall status-bar` (or uninstalling it through the Settings View) as it is meant to be bundled with Atom and not installed manually.
