### ISSUE TITLE
Failed to activate the status-bar package as of 1.0

### ISSUE THREAD

**Issue by arussellsaw** [atom/status-bar#123]
after installing + restarting atom.
```
TypeError: Cannot read property 'onDidChangeStatus' of undefined
    at status-bar-git.GitView.subscribeToRepositories (/Users/alex/.atom/packages/status-bar/lib/git-view.coffee:70:46)
    at status-bar-git.GitView.initialize (/Users/alex/.atom/packages/status-bar/lib/git-view.coffee:19:6)
    at Object.module.exports.activate (/Users/alex/.atom/packages/status-bar/lib/main.coffee:40:10)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

**Comment by thomasjo** [comment]
This package is bundled with Atom and should not be installed manually. As of writing this, the `master` branch of Atom doesn't even use status-bar v1.0.0. Your problem will be resolved by uninstalling your manual installation of status-bar.

If you want to develop on this package, make sure you do so against a build of Atom that is as bleeding edge as possible (aka. run a fresh build against `master` at every day).
