### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeStatus' of undefined

### ISSUE THREAD

**Issue by amosrivera** [atom/status-bar#124]
1. Try to open up project using project switcher

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatus' of undefined

```
At /Users/amosrivera/.atom/packages/status-bar/lib/git-view.coffee:70

TypeError: Cannot read property 'onDidChangeStatus' of undefined
    at status-bar-git.GitView.subscribeToRepositories (/Users/amosrivera/.atom/packages/status-bar/lib/git-view.coffee:70:46)
    at /Users/amosrivera/.atom/packages/status-bar/lib/git-view.coffee:18:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:06.1.0 project-manager:list-projects (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 tree-view:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs",
      "linter-js-standard",
      "linter-csslint",
      "linter-erb",
      "linter-rubocop",
      "linter-tidy",
      "linter-jshint",
      "atom-typescript"
    ]
  },
  "status-bar": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
angularjs-styleguide-snippets, v0.7.3
atom-erb, v0.2.0
atom-pair, v2.0.10
auto-update-packages, v1.0.0
csslint, v1.1.4
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
easy-motion-redux, v1.0.0
editorconfig, v1.2.4
file-icons, v1.6.14
git-diff, v1.0.0
git-plus, vundefined
linter, v1.11.3
linter-eslint, v6.0.0
markdown-preview, v0.157.3
project-manager, v2.7.6
status-bar, v1.0.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
To quote @thomasjo:
>This package is bundled with Atom and should not be installed manually. As of writing this, the master branch of Atom doesn't even use status-bar v1.0.0. Your problem will be resolved by uninstalling your manual installation of status-bar.
If you want to develop on this package, make sure you do so against a build of Atom that is as bleeding edge as possible (aka. run a fresh build against master at every day).

**Comment by Arcanemagus** [comment]
Just had this thrown from v1.7.0-beta0, however I'm guessing that this is probably related to having [svn](https://atom.io/packages/svn) installed.

**Atom Version**: 1.7.0-beta0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatus' of undefined

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\status-bar\lib\git-view.js:99

TypeError: Cannot read property 'onDidChangeStatus' of undefined
    at status-bar-git.GitView.subscribeToRepositories (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\status-bar\lib\git-view.js:99:52)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\status-bar\lib\git-view.js:31:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Project.module.exports.Project.addPath (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\project.js:263:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\atom-environment.js:1101:26)
    at EventEmitter.outerCallback (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta0\resources\app.asar\src\application-delegate.js:244:18)
    at emitThree (events.js:102:20)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "language-markdown",
      "linter-tidy",
      "language-chef",
      "linter-csslint",
      "linter-bootlint",
      "linter-scss-lint",
      "linter-jscs"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
autocomplete-python, v1.7.0
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-docker, v1.1.6
language-elixir, v0.12.3
language-haml, v0.23.15
language-ini, v1.14.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.3
linter-alex, v2.0.0
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-elixirc, v1.1.5
linter-erb, v1.0.2
linter-eslint, v7.1.1
linter-flake8, v1.13.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.2.0
linter-htmlhint, v1.1.0
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jshint, v2.0.3
linter-jsonlint, v1.2.1
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pep8, v1.2.1
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-pylint, v1.2.0
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-stylelint, v2.0.1
linter-tslint, v0.8.3
linter-ui-default, v0.0.2
mapfile-grammar, v0.1.0
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
pigments, v0.24.5
seti-syntax, v0.4.1
seti-ui, v0.9.1
svn, v0.0.9
tab-control, v0.6.9
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Yep, definitely related to having the [svn](https://atom.io/packages/svn) package installed, although I'm not sure why it is being thrown against this package.

**Comment by 50Wliu** [comment]
@Arcanemagus The reason it got thrown here is because there's nothing to suggest `svn` is at fault in the stack trace.

**Comment by Arcanemagus** [comment]
Note for anyone coming here for the same reason: Filed https://github.com/andischerer/atom-svn/issues/20 for that specific package.

**Comment by derwaldgeist** [comment]
Everything worked for me until yesterday. Now I am getting this problem as well. Did either svn or the statusbar plugin change in the meantime?

**Comment by Arcanemagus** [comment]
@derwaldgeist See the linked `atom-svn` issue in the comment above, that is the root issue here, the fact that Atom thinks it is being thrown from the `status-bar` package is a bug (or just a fluke in the call stack, not sure).

**Comment by mrstebo** [comment]
I am getting the same issue after installing atom-hg, and don't have atom-svn installed.

**Comment by mrstebo** [comment]
It turns out atom-hg has the same problem as svn. It is missing the async repository that is how required in Atom 1.7 
[See here](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html)

They will be removing the sync stuff.

**Comment by gnasit** [comment]
why is this closed.? has this been resolved?
for me atleast, i am still getting this issue, and i am on v1.8.0

**Comment by Arcanemagus** [comment]
@gnasit the original (closed) issue was related to trying to update a bundled core plugin. The subsequent stack traces posted so far were all related to the `atom-svn` package, which should supposedly be fixed. Try updating that, and if you are still seeing problems, file a _new_ issue with your full debug information.

**Comment by anweshknayak** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.5
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0
**User**: root

### Stack Trace

Failed to activate the status-bar package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
    at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:32:12)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@anweshknayak Your Atom version is pretty out of date, try updating to the latest stable release and seeing if you still have this issue.
