### ISSUE TITLE
Failed to activate the status-bar package after Atom 1.7.0 update

### ISSUE THREAD

**Issue by mmarinero** [atom/status-bar#143]
It crashes even after restarting Atom and the error reporter points me to this issue https://github.com/atom/status-bar/issues/123

I use the same config and packages in another system that I updated yesterday with no issue so it may be tied to this particular machine.

**Atom Version**: 1.7.0
**System**: Ubuntu 14.04.4
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.1.2

### Stack Trace

Failed to activate the status-bar package

```
At Cannot read property 'onDidChangeStatus' of undefined

TypeError: Cannot read property 'onDidChangeStatus' of undefined
  at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:99:52)
  at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:34:12)
  at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
  at /usr/share/atom/resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
  at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "save-session",
      "save-commands"
    ],
    "ignoredNames": [
      "*.xlsx",
      "*.docx",
      "*.pdf",
      "*.xls",
      "*.doc",
      "*.stbl",
      "*.scht",
      "*.imdt",
      "*.^-",
      "*.png",
      "*.jpg",
      "*.xlsm",
      "*.ppt",
      "*.pptx",
      "*.msg",
      "*.rar",
      "*.zip"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
linter, v1.11.4
linter-eslint, v7.2.0
linter-hlint, v0.4.3
linter-php, v1.2.0
minimap, v4.21.0
pretty-json, v1.0.3
project-manager, v2.9.7
svn, v0.0.9
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by gregtyler** [comment]
Also seeing this on Windows 7 with the following packages in common (all at the same version as mmarinero):
 * linter
 * linter-eslint
 * minimap
 * project-manager
 * svn

**Comment by mbeaudru** [comment]
Same here !

**Comment by eviljoe** [comment]
This is caused by the "svn" package.  Here is the issue in that repo: https://github.com/andischerer/atom-svn/issues/20

The workaround is to disable that package until the bug is fixed (I am not sure which project is at fault).

**Comment by vividtone** [comment]
In my environment, this issue was fixed by disabling nuclide-hg-repository package version 0.0.35.

**Comment by eviljoe** [comment]
@vividtone, I did some research about this and this is what I came up with as far as changes that are necessary for the svn package:

> This is the commit that broke the svn package: https://github.com/atom/status-bar/pull/114/commits/aa4c4fe3e9444d14973bbb69e41ca593895e507a.  It is part of the move to async git: https://github.com/atom/atom/pull/9213.
> 
> The status bar is looking for an `async` field on the [`SvnRepository`](https://github.com/andischerer/atom-svn/blob/master/lib/svn-repository.coffee) object.  For the [`GitRepository`](https://github.com/atom/atom/blob/master/src/git-repository.coffee) class, that object is an instance of [`GitRepositoryAsync`](https://github.com/atom/atom/blob/master/src/git-repository-async.js)
> 
> To keep up with the new "API," it seems like each of the functions in the `SvnRepository` class will have to be replicated on a new class, `SvnRepositoryAsync`.  Each of the getter functions (or maybe all functions) in `SvnRepositoryAsync` will have to return a promise that resolves to the requested value.

**Comment by Shiho06** [comment]
Updated svn package to 0.0.10 today, everything seems to be ok.

**Comment by Shiho06** [comment]
Just updated svn package to 0.0.10, everything seems to be ok now.

**Comment by ruppalsingh** [comment]
I do not have SVN installed but still receive this error, after updating from 1.4.0 to 1.8.0.

I have tried disabling all my packages to no avail. Atom sends me here. Any ideas?

**Comment by lowercase24** [comment]
I did a clean install and I am hitting this issue.  I am on ubuntu 16.04 running atom 1.8.0.

**Comment by 50Wliu** [comment]
@ruppalsingh @lowercase24 please see atom/atom#12182.

**Comment by Yajo** [comment]
atom/atom#12182 worked for me

**Comment by Guard13007** [comment]
I'm having this issue on a fresh install of Atom, nothing has been added, I've rebooted, it always opens and gives me an error and points here. I'm on Ubuntu 14.04.4

I tried following the instructions in atom/atom#12182 and now I don't get the error message, but I still can't open a project folder.

**Comment by renan-taranto** [comment]
@Guard13007 If you are new to Atom (as I am) this may help: try pressing **Ctrl+\** to open the Tree View.

**Comment by CarlosRoque** [comment]
I am having the same issue. clean ubuntu 16.04 install

**Comment by 50Wliu** [comment]
@CarlosRoque please see atom/atom#12182.

**Comment by CarlosRoque** [comment]
@50Wliu that fixed it for me. scrolled down to where the downloadable package is and that worked.

**Comment by Yakoot** [comment]
I've installed the latest version of Atom

**Atom Version**: 1.8.0
**System**: Linux Mint
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package, v1.1.0


### Stack Trace

Failed to activate the git-diff package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at GitDiffView.module.exports.GitDiffView.subscribeToRepository (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:129:48)
    at new GitDiffView (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:19:12)
    at /usr/share/atom/resources/app.asar/node_modules/git-diff/lib/main.js:23:9
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:307:9)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/main.js:22:29)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@Yakoot please see atom/atom#12182.

**Comment by Yakoot** [comment]
@50Wliu 12182 not working for me, will try the beta-version, maybe it solve my  problem, like solves in https://github.com/atom/atom/issues/12182#issuecomment-234216275

**Comment by davividal** [comment]
Same here, brand new install. Fedora 23.

**Comment by AshBT** [comment]
I just reverted to the 1.7.4 version.

The problem started on my end when I did a hard - reload (CTRL + ALT + R)

**Comment by 50Wliu** [comment]
@davividal @AshBT please see atom/atom#12182.

As people do not seem to be reading any of the comments before commenting, I'm locking this issue.

# If you are experiencing this issue, please follow the instructions in [atom/atom#12812](https://github.com/atom/atom/issues/12182).
