### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastSelection' of undefined

### ISSUE THREAD

**Issue by karen818** [atom/status-bar#145]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getLastSelection' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

TypeError: Cannot read property 'getLastSelection' of undefined
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/selection-count-view.js:59:56
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2256:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:930:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:264:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:396:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:342:12)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:256:18)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1333:79)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:879:14)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Object.module.exports.autosavePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:58:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:23:26
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:152:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:431:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:533:18
    at process._tickCallback (node.js:392:9)
```

### Commands

```
  2x -5:13.9.0 tree-view:open-selected-entry-right (span.name.icon.icon-file-text)
     -4:50.4.0 tabs:split-down (li.texteditor.tab.sortable.active.right-clicked)
     -4:34.4.0 markdown-preview:preview-file (span.name.icon.icon-book)
     -4:06.8.0 tabs:split-down (li.texteditor.tab.sortable.active.right-clicked)
  2x -3:23.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:14.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:09.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:04.0 core:copy (atom-text-editor.editor.is-focused)
     -0:55.7.0 settings-view:show-keybindings (atom-text-editor.editor.is-focused)
     -0:01.2.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bracket-close-jump",
      "close-tags",
      "atom-like-brackets-editor",
      "autoclose-html",
      "autocomplete-html-entities",
      "color-picker",
      "linter-htmlhint",
      "htmlhint"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
emmet, v2.4.3
linter, v1.11.4
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by lynxman** [comment]
[Enter steps to reproduce below:]

1. Open Project folder that uses mercurial
2. Open modified file that has not been commited yet

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1


### Stack Trace

Uncaught TypeError: Cannot read property 'ahead' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213

TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:213:78)
    at status-bar-git.GitView.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:81:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:562:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:639:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:690:17)
```

### Commands

```
     -0:29.1.0 open-recent:File0-/Volumes/Code/iwith/puppet‐abcore/site-modules/profiles/manifests/base.pp (atom-text-editor.editor.is-focused)
     -0:23 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide"
    ],
    "packagesWithKeymapsDisabled": [
      "aligner"
    ],
    "projectHome": "/Volumes/Code",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.3 (inactive)
align-regexp, v0.2.0 (inactive)
aligner, v0.22.1 (active)
aligner-css, v1.2.0 (active)
aligner-javascript, v1.0.0 (active)
aligner-lua, v1.0.0 (active)
aligner-puppet, v0.1.1 (active)
aligner-python, v1.0.1 (active)
aligner-ruby, v1.5.0 (active)
aligner-scss, v1.1.0 (active)
ansible-snippets, v0.2.0 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-cform, v0.6.0 (inactive)
atom-hg, v2.0.5 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
auto-detect-indentation, v1.1.0 (active)
autocomplete-awk, v0.1.2 (active)
autocomplete-go, v1.1.0 (active)
autocomplete-json, v5.1.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-python, v1.8.6 (active)
autocomplete-ruby, v0.1.0 (active)
builder-go, v1.0.0 (active)
file-icons, v1.7.18 (active)
git-blame, v0.4.11 (inactive)
git-diff-details, v1.3.0 (active)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.1 (active)
go-get, v1.0.3 (active)
go-plus, v4.1.0 (active)
godef, v0.2.5 (inactive)
gofmt, v1.1.6 (active)
gometalinter-linter, v1.1.0 (active)
gorename, v1.0.2 (active)
highlight-selected, v0.11.2 (active)
language-ansible, v0.1.11 (active)
language-awk, v0.1.11 (active)
language-chef, v0.9.0 (active)
language-nginx, v0.6.1 (active)
language-puppet, v0.20.0 (active)
language-terraform, v0.7.4 (active)
language-tmux, v0.4.0 (active)
linter, v1.11.16 (active)
linter-erb, v1.0.2 (active)
linter-golinter, v1.2.0 (active)
linter-json-lint, v0.1.1 (active)
linter-markdown, v2.0.0 (active)
linter-perl-lint, v0.1.2 (active)
linter-puppet-lint, v0.7.0 (active)
linter-python, v3.0.5 (active)
linter-ruby, v1.2.2 (active)
linter-ruby-lint, v1.2.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-hide, v0.3.0 (active)
multi-cursor, v2.1.3 (inactive)
navigator-godef, v1.0.3 (active)
open-recent, v5.0.0 (active)
pigments, v0.31.2 (active)
python-tools, v0.6.8 (active)
save-session, v0.15.7 (active)
sync-settings, v0.7.2 (active)
tester-go, v1.0.4 (active)
toggle-quotes, v1.0.0 (inactive)
wrap-guide, v0.38.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
