### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ahead' of null

### ISSUE THREAD

**Issue by unclekitty** [atom/status-bar#162]
TypeError: Cannot read property 'ahead' of null
    at status-bar-git.GitView.updateAheadBehindCount (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\status-bar\lib\git-view.js:213:78)
    at status-bar-git.GitView.update (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\status-bar\lib\git-view.js:171:12)
    at status-bar-git.GitView.subscribeToActiveItem (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\status-bar\lib\git-view.js:81:19)
    at C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\status-bar\lib\git-view.js:24:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\src\pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\src\pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\src\pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\mi\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:660:19)

The error was thrown from the status-bar package. This issue has already been reported.

**Comment by 50Wliu** [comment]
> This issue has already been reported.

#161.

Temporarily disable any hg or svn packages you're using until they're updated.  Sorry for the inconvenience.
