### ISSUE TITLE
Can not find module `atom-space-pen-views`

### ISSUE THREAD

**Issue by iMagdy** [atom/status-bar#187]
![image](https://cloud.githubusercontent.com/assets/611426/24709665/f3150386-1a1a-11e7-8363-dee1d0d46a39.png)

[Enter steps to reproduce:]

1. Open Atom

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.1

### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/terminal-fusion/lib/status-bar.coffee:2:25)
    at /packages/terminal-fusion/lib/status-bar.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.consumeStatusBar (/packages/terminal-fusion/lib/terminal-fusion.coffee:17:27)
    at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:396:71)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:352:19
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
    at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
    at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:07.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-sk-light-syntax.theme-native-ui)
     -1:00.3.0 settings-view:open (input.hidden-input)
     -0:56.6.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:54 pane:show-item-1 (input.hidden-input)
     -0:53.2.0 core:close (input.hidden-input)
     -0:44 pane:show-next-recently-used-item (input.hidden-input)
     -0:43.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:37.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:37.6.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
adventurous-syntax 0.2.0 
aesthetic-ui 2.0.0 
an-old-hope-syntax 1.0.4 
ansible-snippets 0.2.0 
apex-syntax 0.1.0 
api-docs undefined 
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-carbonightblue 0.1.0 
atom-center-comment 0.1.1 
atom-gooey-syntax 1.0.0 
atom-handlebars 1.3.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
autohide-tree-view 0.25.1 
bone-a-kite 1.0.0 
bonfire-syntax 1.0.0 
bonfire-ui 0.1.3 
brilliance-white-theme 0.2.1 
busy-signal 1.3.0 
bzzz-black 2.0.0 
cake-syntax 1.0.2 
carbon-blue-atom 2.1.1 
chester-atom-syntax 0.1.1 
climate-syntax 5.0.0 
cold-syntax 1.3.0 
cold-ui 1.4.0 
colibri-light-syntax 0.3.0 
cranberry-syntax 1.2.0 
css-snippets 1.1.0 
dark-flat-ui 1.2.4 
deep-space-syntax 1.1.0 
dlighted-syntax 0.3.1 
docblockr 0.9.4 
duotone-snow 2.0.2 
eclectic-syntax 0.2.1 
editorconfig 2.2.2 
electron-dark-syntax 1.0.1 
emmet 2.4.3 
es6-javascript 1.0.0 
ficus-dark-syntax 2.0.0 
file-icons 2.1.2 
firewatch-syntax 1.1.1 
fizzy 0.21.0 
fizzy-dark 0.18.2 
flatwhite-syntax 0.8.0 
genesis-ui 0.5.0 
gloom 0.4.12 
gruvbox 1.0.7 
gruvbox-plus-syntax 1.3.1 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
Handlebars 1.7.1 
highlight-selected 0.13.1 
hyperspace-syntax 0.1.4 
ice-cold-syntax 0.1.0 
imdone-atom-github 0.1.11 
intentions 1.1.2 
jonikorpi-atom-theme-ui 4.4.1 
json-converter 0.2.4 
kimbie-dark 2.0.2 
kimi-syntax 0.3.1 
kyaho-dark-syntax 1.0.0 
language-ansible 0.2.1 
language-arduino 0.4.3 
language-babel 2.57.2 
language-diff 0.7.0 
language-docker 1.1.7 
language-dotfiles 1.0.0 
language-graphql 0.8.0 
language-html5-subtlegradient 0.1.0 
language-jade 0.7.2 
language-nginx 0.7.0 
language-roff 1.2.2 
linter 2.1.2 
linter-eslint 8.1.4 
linter-jsonlint 1.3.0 
linter-package-json-validator 1.0.1 
linter-scss-lint 3.1.0 
linter-shellcheck 1.4.4 
linter-tslint 0.15.0 
linter-ui-default 1.2.2 
Lucario 2.0.0 
mahou-shoujo-syntax 0.2.0 
markdown-pdf 1.5.0 
minimap 4.27.0 
native-ui 0.20.4 
nativescript-ng2-atom-snippets 1.2.0 
Neka-Syntax 1.0.1 
neutron-syntax 0.7.0 
neutron-ui 0.4.0 
new-era-syntax 1.1.0 
newton-dark-syntax 1.1.7 
newton-dark-ui 1.1.2 
next-dark 0.2.0 
no-caffeine-syntax 0.18.0 
nord-atom-syntax 0.7.0 
nord-atom-ui 0.11.0 
northem-dark-atom-ui 2.0.0 
octocat-syntax 1.3.1 
one-dark-atom 1.3.0 
open-in-deckset 0.1.0 
pane-full-info 2.0.0 
pigments 0.39.1 
pipe 0.4.0 
polaris-syntax 0.1.0 
predawn-syntax 1.0.4 
project-manager 3.3.4 
ramda-syntax 0.12.0 
redui-jm-syntax 1.4.0 
set-syntax 0.3.2 
simple-align 0.2.0 
sk-light-syntax 1.0.1 
skel-dark-syntax 1.1.1 
slack-ui 0.8.0 
slime 2.1.0 
slut-syntax 2.0.0 
smart-tab-name 1.0.5 
sort-lines 0.14.0 
spectrum-light-syntax 0.0.5 
tabs-closer 0.14.0 
tabularize 0.2.5 
terminal-fusion 2.4.4 
todo-show 1.11.0 
tradeship 0.0.1 
trendy-dark-syntax 0.2.0 
twofold-syntax 0.0.2 
vim-mode 0.66.0 
wakatime 6.0.13 
white-ui 2.6.2 
xcode-syntax 0.1.0 
xcode-theme 1.4.0 
```

**Comment by 50Wliu** [comment]
Please report this to the [terminal-fusion](https://atom.io/packages/terminal-fusion) package instead.

**Comment by iMagdy** [comment]
Thanks @50Wliu
