### ISSUE TITLE
Uncaught TypeError: Cannot read property 'priority' of undefined

### ISSUE THREAD

**Issue by Eastegg** [atom/status-bar#188]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'priority' of undefined

```
At C:\Users\FE-Tian\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\status-bar\lib\status-bar-view.js:53

TypeError: Cannot read property 'priority' of undefined
    at StatusBarView.module.exports.StatusBarView.addLeftTile (/app.asar/node_modules/status-bar/lib/status-bar-view.js:53:130)
    at updateStatusbar (/packages/jshint/index.js:119:13)
    at registerEvents (/packages/jshint/index.js:284:2)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Pane.module.exports.Pane.observeActiveItem (/app.asar/src/pane.js:241:7)
    at /app.asar/src/pane-container.js:346:42
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/app.asar/src/pane-container.js:198:22)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:850:14)
    at Pane.module.exports.Pane.focus (/app.asar/src/pane.js:252:21)
    at /app.asar/src/pane-element.js:50:23)
```

### Commands

```
     -0:59.9.0 core:confirm (input.hidden-input)
     -0:47 core:select-all (input.hidden-input)
     -0:46.9.0 core:paste (input.hidden-input)
     -0:46.5.0 core:confirm (input.hidden-input)
     -0:42 core:select-all (input.hidden-input)
     -0:42 core:paste (input.hidden-input)
     -0:41.5.0 core:confirm (input.hidden-input)
     -0:26 core:select-all (input.hidden-input)
     -0:25.9.0 core:paste (input.hidden-input)
     -0:25.2.0 core:confirm (input.hidden-input)
     -0:20.2.0 core:select-all (input.hidden-input)
     -0:20.2.0 core:paste (input.hidden-input)
     -0:19.5.0 core:confirm (input.hidden-input)
     -0:06.7.0 core:select-all (input.hidden-input)
     -0:06.6.0 core:paste (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-css-comb 3.1.0 
atom-ctags 5.0.0 
atom-dark-fusion-syntax 2.2.0 
atom-jshint 2.0.0 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-ternjs 0.18.2 
autoclose-html 0.23.0 
autocomplete-json 5.4.0 
autoprefixer 3.6.1 
batman-syntax 1.1.0 
bottom-dock 0.4.4 
busy-signal 1.3.0 
color-picker 2.2.5 
eclectic-syntax 0.2.1 
emmet 2.4.3 
file-icons 2.1.2 
flatwhite-syntax 0.8.0 
git-log 0.4.1 
git-plus 7.3.3 
gulp-manager 0.2.19 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
jshint 1.8.6 
linter 2.1.2 
linter-csslint 1.3.4 
linter-eslint 8.1.5 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-manager 0.2.12 
linter-markdown 3.1.0 
linter-php 1.3.2 
linter-ui-default 1.2.2 
lunar-particle-syntax 0.3.8 
lunar-particle-ui 0.3.13 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
monokai-seti 0.7.0 
node_modules undefined 
nucleus-dark-ui 0.11.10 
open-in-browsers 0.0.19 
paraiso-black 1.0.5 
paraiso-dark 2.0.2 
pigments 0.39.1 
relative-numbers 0.7.1 
seti-syntax 1.1.3 
seti-ui 1.7.0 
vue-autocomplete 0.1.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [jshint package](https://atom.io/packages/jshint) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
