### ISSUE TITLE
Uncaught TypeError: Cannot read property 'priority' of undefined

### ISSUE THREAD

**Issue by zhuangyin8** [atom/status-bar#190]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by zhuangyin8** [comment]
The error was thrown from the status-bar package. This issue has already been reported.

**Comment by zhuangyin8** [comment]
Project
stylin3_code_files
All Site Source
CSS3 加载中@
JavaScript Traffic Light
Sublime Text The text editor you'll fall in love with
That's what I have always wished. -liguanjian坦克大战(BattleCity)@
Yandex
Yandex@
开 奖
www.treejs.cn
tmp
colorBall4
audio
button.ogg
cheer.ogg
lottery.ogg
selectBall.ogg
img
background.jpg
boxBack.png
boxDark.png
boxFront.png
button_bg.png
js
ball.js
jquery.js
ball.css
ball.html
木兰天池官方网站-普通登录
CSS3 加载中@.zip
Damonare的个人博客.zip
Javascript State Machine v2.zip
JavaScript Traffic Light2.zip
Stylin’ with CSS - free code Learn CSS jQuery PHP Tutorials Books.zip
Sublime Text The text editor you'll fall in love with.zip
That's what I have always wished. -liguanjian(坦克大战(BattleCity) )@.zip
The Aviator The Game Codrops.zip
Viosey's Blog Material Design Theme for Hexo.zip
Yandex@.zip
开 奖.zip
木兰天池官方网站-普通登录@.zip
木兰天池官方网站-注册.zip
登录-乐蜂网.zip
纯CSS3实现圆盘时钟动画DEMO演示.zip
网易·有钱.zip
网易有钱-特省心的记账理财应用.zip
首页 IT修真院 更快更高效的免费Java,CSS,JS,运维技术培训.zip
黑科云下载器-官网.zip
ball.html
jquery.js
ball.js
background.jpg
whiteblacktransparent
-100%+
Zoom to fit

ball.html Preview

开 奖\www.treejs.cn\tmp\colorBall4\audio\cheer.ogg1:1
Mixed1 deprecationUTF-8Plain Text
Uncaught TypeError: Cannot read property 'priority' of undefined
C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\status-bar\lib\status-bar-view.js:55
Hide Stack Trace
TypeError: Cannot read property 'priority' of undefined
    at StatusBarView.module.exports.StatusBarView.addLeftTile (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\status-bar\lib\status-bar-view.js:55:1)
    at ImageEditorStatusView.attach (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\image-view\lib\image-editor-status-view.js:53:1)
    at new ImageEditorStatusView (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\image-view\lib\image-editor-status-view.js:43:1)
    at Object.attachImageEditorStatusView (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\image-view\lib\main.js:50:1)
    at C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\image-view\lib\main.js:23:1
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:141:1)
    at Workspace.didChangeActivePaneItemOnPaneContainer (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\workspace.js:489:1)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\workspace-center.js:16:1)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\event-kit\lib\emitter.js:141:1)
    at PaneContainer.didChangeActiveItemOnPane (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\pane-container.js:280:1)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\pane.js:318:1)
    at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\pane.js:454:1)
    at Pane.module.exports.Pane.activatePreviousItem (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\pane.js:419:1)
    at Pane.module.exports.Pane.removeItem (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\pane.js:609:1)
    at Pane.module.exports.Pane.destroyItem (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\src\pane.js:682:1)
    at TabBarView.module.exports.TabBarView.closeTab (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\tabs\lib\tab-bar-view.js:339:1)
    at HTMLDivElement.TabView.didClickCloseIcon (C:\Users\zhuan_f\AppData\Local\atom\app-1.17.0-beta1\resources\app\node_modules\tabs\lib\tab-bar-view.js:227:1)
The error was thrown from the status-bar package. This issue has already been reported.
View Issue
