### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by vikasv** [atom/status-bar#210]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.11

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\vikas\AppData\Local\atom\app-1.19.7\resources\app\src\decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (~/AppData/Local/atom/app-1.19.7/resources/app/src/decoration-manager.js:183:27)
    at TextEditor.module.exports.TextEditor.decorateMarker (~/AppData/Local/atom/app-1.19.7/resources/app/src/text-editor.js:1811:43)
    at new Selection (~/AppData/Local/atom/app-1.19.7/resources/app/src/selection.js:35:43)
    at TextEditor.module.exports.TextEditor.addSelection (~/AppData/Local/atom/app-1.19.7/resources/app/src/text-editor.js:2647:25)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:79:24
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/text-buffer/lib/marker-layer.js:438:28)
    at MarkerLayer.module.exports.MarkerLayer.markRange (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/text-buffer/lib/marker-layer.js:225:25)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:105:58)
    at TextEditor.module.exports.TextEditor.addSelectionForBufferRange (~/AppData/Local/atom/app-1.19.7/resources/app/src/text-editor.js:2321:40)
    at TextEditor.module.exports.TextEditor.createLastSelectionIfNeeded (~/AppData/Local/atom/app-1.19.7/resources/app/src/text-editor.js:2713:27)
    at TextEditor.module.exports.TextEditor.getLastCursor (~/AppData/Local/atom/app-1.19.7/resources/app/src/text-editor.js:2127:18)
    at TextEditor.module.exports.TextEditor.getCursorBufferPosition (~/AppData/Local/atom/app-1.19.7/resources/app/src/text-editor.js:1906:25)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/status-bar/lib/cursor-position-view.js:110:82
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.7/resources/app/src/view-registry.js:187:15)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/view-registry.js:3:65
```

### Commands

```
  2x -0:36.6.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
