### ISSUE TITLE
target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by timfallmk** [atom/status-bar#216]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`target[Symbol.iterator] is not a function` When loading status-bar.

This appears to happen only with the new (see below) beta version.

### Steps to Reproduce

1. Launch Atom beta

**Expected behavior:**
Load `status-bar` package

**Actual behavior:** 
`status-bar` does not load

**Reproduces how often:**
Every time (%100)

### Versions

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.14

### Stack Trace

Failed to activate the status-bar package

```
At target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/Applications/Atom Beta.app/Contents/Resources/app/src/tooltip-manager.js:117:35)
    at StatusBarView.attach (/packages/build/lib/status-bar-view.js:26:34)
    at /packages/build/lib/status-bar-view.js:9:55
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:155:27)
    at /packages/build/lib/status-bar-view.js:9:17)
    at Object.consumeStatusBar (/packages/build/lib/build.js:331:26)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
accents-ui 1.3.0 
activate-power-mode 2.6.0 
adventurous-syntax 0.2.0 
aligner 1.2.4 
aligner-javascript 1.3.0 
api-docs 0.0.6 
ariake-dark-syntax 0.1.3 
asciidoc-preview 2.10.3 
aligner-golang 0.1.0 
atom-html-preview 0.2.2 
atom-text-transformer 0.7.0 
atomatigit 1.5.5 
atomic-chrome 0.3.2 
auto-detect-indentation 1.3.0 
auto-update-packages 1.0.1 
autocomplete 0.47.0 
autocomplete-emojis 2.5.0 
autocomplete-python 1.10.3 
autocomplete-swift 1.0.3 
base16-eighties-one-dark 1.0.0 
block-comment 0.4.3 
build 0.69.0 
build-dockerfile 1.0.1 
busy 0.7.0 
busy-signal 1.4.3 
circle-ci 0.10.1 
Clean 0.10.0 
Clean2 0.16.0 
commitment 0.1.3 
environment 1.3.1 
feedback 0.38.0 
flask-snippets 0.3.3 
flatwhite-syntax 0.8.1 
floobits 0.32.12 
gist 1.1.0 
git-control 0.9.0 
git-go 1.0.5 
git-plus 7.10.0 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
gloom 0.6.4 
glowing-cursor 0.1.2 
go-debug 1.5.2 
go-oracle 0.2.1 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
gotests 0.3.0 
intentions 1.1.5 
isotope-light-ui 2.3.0 
isotope-ui 2.8.5 
kite 0.52.0 
language-asciidoc 1.11.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-fish-shell 1.0.5 
language-gitignore 0.3.0 
language-hcl 0.4.0 
language-javascript-jsx 0.3.7 
language-nginx 0.8.0 
language-puppet 0.23.0 
language-restructuredtext 1.1.0 
language-scala 1.1.9 
language-swift 0.5.0 
language-systemd 0.1.1 
language-terraform 0.8.1 
language-unix-shell 0.40.1 
linkify 0.11.0 
linter 2.2.0 
linter-golinter 1.2.2 
linter-puppet 1.0.0 
linter-rst 0.0.3 
linter-scalac 1.4.4 
linter-swiftc 2.0.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
markdown-pdf 2.1.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-git-diff 4.3.1 
monokai 0.24.0 
neon-cursor 1.6.0 
neon-selection 0.3.2 
nucleus-dark-ui 0.12.3 
polaris-syntax 0.1.0 
polymorph-ui 1.8.8 
pretty-json 1.6.4 
rain-syntax 2.0.2 
rain-ui 1.0.1 
rainy-night-syntax 0.3.2 
release-notes 0.53.0 
seti-syntax 1.0.1 
seti-ui 1.9.0 
shadow 0.1.0 
shadow-syntax 0.1.0 
sholight 0.2.0 
sourcerer 2.0.0 
sync-settings 0.8.3 
termination 0.6.1 
the-closer 0.7.0 
transform 0.4.0 
tree-view-git-branch 0.1.2 
typewriter 0.7.0 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
Zen 0.18.0 
```

**Comment by timfallmk** [comment]
As a further note, the dialogue appears to incorrect link to #176

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom#16135.  Thanks for creating the issue!
