### ISSUE TITLE
Failed to activate the status-bar package

### ISSUE THREAD

**Issue by LKC314** [atom/status-bar#217]
1. Open Atom.

**Atom**: 1.21.2 ia32
**Electron**: 1.6.15
**OS**: Windows 8 32-bit
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.13

### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'etch'

Error: Cannot find module 'etch'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Atom-LaTeX-master/lib/view/status.js:20:13)
    at /packages/Atom-LaTeX-master/lib/view/status.js:32:17)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.21.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.2/resources/app/src/native-compile-cache.js:66:33)
    at Object.consumeStatusBar (/packages/Atom-LaTeX-master/lib/main.coffee:86:16)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:690:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:439:30)
    at ~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:245:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-latex 0.8.2 
simplified-chinese-menu 5.3.4 
autocomplete-haskell 1.0.1 
gpp-compiler 3.0.7 
haskell-ghc-mod 2.1.3 
haskell-ghc-mod 2.1.3 
haskell-grammar 0.4.0 
ide-haskell 2.2.0 
ide-haskell-hasktags 0.0.12 
language-haskell 1.14.3 
language-latex 1.1.1 
language-latex 1.1.1 
language-pascal 0.20.2 
latex 0.49.0 
linter-gcc 0.7.1 
pdf-view undefined 
script 3.17.3 
seti-ui 1.9.0 
simplified-chinese-menu 5.3.4 
```

**Comment by rsese** [comment]
Based on the stack trace, I think this is related to one of your LaTex packages, [Atom-LaTeX](https://github.com/James-Yu/Atom-LaTeX) I think.

It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

But if you can still reproduce the error in safe mode (`atom --safe`), please let me know.

**Comment by aadrian** [comment]
1. Open Atom
This error still happens, and this is the plug-in that breaks, since Atom is reporting to this one :) .

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.15


### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:6:11)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:6:19)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.27.2/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at Object.addStatusBarItemsIfReady (/packages/foldingtext-for-atom/lib/foldingtext.coffee:137:29)
    at Object.consumeStatusBarService (/packages/foldingtext-for-atom/lib/foldingtext.coffee:130:6)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:397:75)
```

### Commands

```
```

### Non-Core Packages

```
atom-grails 1.2.0 
build 0.70.0 
build-powershell 0.11.0 
busy-signal 1.4.3 
cucumber 0.6.0 
emmet 2.4.3 
file-icons 2.1.21 
foldingtext-for-atom 0.9.2 
intentions 1.1.5 
language-gradle 0.0.5 
language-groovy 0.7.0 
language-powershell 4.0.1 
language-prolog 0.11.0 
language-scala 1.1.9 
linter 2.2.0 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.3.0 
markdown-writer 2.7.3 
open-terminal-here 2.3.2 
permanent-delete 0.1.7 
project-manager 3.3.6 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
Zen 0.18.0 
```

**Comment by andrei-elizaga** [comment]
1. Open atom from the terminal.

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.15


### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:6:11)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:6:19)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.addStatusBarItemsIfReady (/packages/foldingtext-for-atom/lib/foldingtext.coffee:137:29)
    at Object.consumeStatusBarService (/packages/foldingtext-for-atom/lib/foldingtext.coffee:130:6)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.1 
custom-title 1.0.1 
file-watcher 1.2.6 
foldingtext-for-atom 0.9.2 
intentions 1.1.2 
linter 2.1.4 
linter-flake8 2.3.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.7.1 
minimap 4.29.8 
monokai 0.24.0 
react 0.18.0 
script 3.18.1 
Sublime-Style-Column-Selection 1.7.4 
symbol-gen 1.3.1 
```

**Comment by Arcanemagus** [comment]
@aadrian The resolver for which package to blame isn't always accurate, the stack trace is the only way to tell in many cases. For your case the error was being caused by the [foldingtext-for-atom](https://atom.io/packages/foldingtext-for-atom) package.

@andrei-elizaga from your stack trace it looks like you are _also_ being brought here by the same bug in that package.

If one of you files a bug about this on the [issue list](https://github.com/FoldingText/foldingtext-for-atom/issues) for that package that would be the best way forward for getting that resolved 😉.

**Comment by liuran** [comment]
1. open Atom and and this error message happens

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**System**: Mac OS X 10.14
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1


### Stack Trace

Failed to activate the status-bar package

```
At atom.tooltips.findTooltips is not a function

TypeError: atom.tooltips.findTooltips is not a function
    at AtomClockView.setTooltip (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock-view.js:142:21)
    at AtomClockView.initialize (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock-view.js:19:10)
    at AtomClockView.start (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock-view.js:14:10)
    at Object.consumeStatusBar (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock.js:63:24)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:362:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28
```

### Commands

```
     -0:01.0 nuclide-file-tree:toggle (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:01.0 nuclide-file-tree:reveal-active-file (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:01.0 nuclide-file-tree:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.0 nuclide-file-tree:reveal-active-file (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:01.0 nuclide-file-tree:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.0 nuclide-file-tree:reveal-active-file (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:01.0 nuclide-file-tree:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-clock, v0.1.16 (inactive)
color-picker, v2.3.0 (inactive)
git-plus, v7.0.7 (inactive)
language-vue, v0.23.1 (inactive)
nord-atom-syntax, v0.5.0 (inactive)
nord-atom-ui, v0.9.0 (inactive)
nuclide, v0.194.0 (inactive)
script, v3.18.1 (inactive)
vim-mode-plus, v0.66.1 (inactive)
vim-modeline, v0.5.2 (inactive)
vue-element-ui-snippets, v0.7.0 (inactive)
vue-fmt, v0.1.1 (inactive)
vue-format, v0.4.0 (inactive)
vue-snippets, v0.6.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by rsese** [comment]
Thanks @liuran - from your stack trace, it looks like the issue is with the https://atom.io/packages/atom-clock package.  You can file an issue in the package repository to let them know about the problem.
