### ISSUE TITLE
Failed to activate the status-bar package

### ISSUE THREAD

**Issue by menghuazou** [atom/status-bar#237]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.17

### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'etch'
Require stack:
- C:\Users\邹孟华\.atom\packages\Atom-LaTeX-master\lib\view\status.js
- C:\Users\邹孟华\.atom\packages\Atom-LaTeX-master\lib\main.coffee
- C:\Users\邹孟华\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

Error: Cannot find module 'etch'
Require stack:
- C:\Users\邹孟华\.atom\packages\Atom-LaTeX-master\lib\view\status.js
- C:\Users\邹孟华\.atom\packages\Atom-LaTeX-master\lib\main.coffee
- C:\Users\邹孟华\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/Atom-LaTeX-master/lib/view/status.js:20:13)
    at /packages/Atom-LaTeX-master/lib/view/status.js:32:17)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at Object.consumeStatusBar (/packages/Atom-LaTeX-master/lib/main.coffee:87:16)
    at Provider.provide (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1060527)
    at ServiceHub.provide (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3293339)
    at Package.activateServices (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3301625)
    at Package.activateNow (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3298601)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297925
    at Package.measure (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3295535)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297785
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3297728)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:382738)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:382354
    at Config.transactAsync (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:332002)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:382304)
    at PackageManager.activate (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:381854)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:757178
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-latex 0.9.1 
pdf-view 0.72.0 
browser-plus 0.0.98 
language-latex 1.2.0 
```

**Comment by iterating** [comment]
Having this issue as well.
