### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by atalargo** [atom/status-bar#49]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.57.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:97

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  at Error (native)
  at status-bar.StatusBarView.addRightTile (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:97:23)
  at StatusBarSummaryView.render (/Users/fruardum/.atom/packages/linter/lib/statusbar-summary-view.coffee:25:23)
  at LinterView.updateViews (/Users/fruardum/.atom/packages/linter/lib/linter-view.coffee:193:27)
  at /Users/fruardum/.atom/packages/linter/lib/linter-view.coffee:111:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:328:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/Users/fruardum/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Users/fruardum/.atom/packages/project-manager/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -4:54.9 project-manager:save-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:52.6 core:confirm (input.native-key-bindings)
  2x -4:52.6 focus (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -4:44.7 project-manager:edit-projects (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -4:36.1 core:close (atom-text-editor.editor)
     -0:00.0 incompatible-packages:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
atom-lint, v0.20.1
autocomplete-plus, v1.1.0
behat-atom, v0.1.2
coffee-lint, v0.7.3
jsonlint, v1.0.0
language-twig, v1.5.2
linter, v0.10.1
linter-csslint, v0.0.11
linter-flow, v0.1.3
linter-haml, v0.1.0
linter-php, v0.0.11
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
linter-scss-lint, v0.0.11
php-twig, v3.0.0
project-manager, v1.15.0
rsense, v0.6.0
ruby-block-converter, v3.0.0
script, v2.16.0
symbols-tree-view, v0.3.2
symfony-snippets, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Can you share some steps for how to reproduce this please?
Also, if possible, could you try to reproduce this in safe mode (`atom --safe`)?

**Comment by mik01aj** [comment]
The same for me. It happens repeatedly when I focus some editor with js code. I suspect that one of the linters is guilty here.

**Comment by kevinsawicki** [comment]
Closing in favor of the linter package issue @mik01aj reported, https://github.com/AtomLinter/Linter/issues/503
