### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by papermoon1978** [atom/status-bar#61]
[Enter steps to reproduce below:]

nothing special - I'm just opening one of my recent projects. The issue happens with all of them. Before the update, everything was fine.

**Atom Version**: 0.182.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.63.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\andre lerche\.atom\packages\status-bar\lib\git-view.coffee:81

TypeError: undefined is not a function
  at status-bar-git.GitView.getRepositoryForActiveItem (C:\Users\andre lerche\.atom\packages\status-bar\lib\git-view.coffee:81:30)
  at status-bar-git.GitView.update (C:\Users\andre lerche\.atom\packages\status-bar\lib\git-view.coffee:93:13)
  at C:\Users\andre lerche\.atom\packages\status-bar\lib\git-view.coffee:69:10
  at Emitter.module.exports.Emitter.emit (C:\Users\andre lerche\AppData\Local\atom\app-0.182.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Task.callback (C:\Users\andre lerche\AppData\Local\atom\app-0.182.0\resources\app\src\git-repository.js:429:34)
  at C:\Users\andre lerche\AppData\Local\atom\app-0.182.0\resources\app\src\task.js:68:72
  at Task.module.exports.Emitter.emit (C:\Users\andre lerche\AppData\Local\atom\app-0.182.0\resources\app\node_modules\emissary\lib\emitter.js:118:15)
  at ChildProcess.<anonymous> (C:\Users\andre lerche\AppData\Local\atom\app-0.182.0\resources\app\src\task.js:81:31)
  at ChildProcess.emit (events.js:119:17)
  at handleMessage (child_process.js:326:10)
  at Pipe.channel.onread (child_process.js:354:11)

```

### Commands

```
     -0:13.4 open-recent:open-recent-path-4 (atom-pane.pane.active)
     -0:13.3 tree-view:toggle-focus (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.git",
      "*.hg",
      "*.svn",
      "*.DS_Store",
      "*.Thumbs.db",
      "*.exe",
      "*.db"
    ],
    "disabledPackages": [
      "tabs",
      "save-session",
      "vim-mode",
      "wrap-guide",
      "keyboard-localization"
    ],
    "projectHome": "d:\\dev\\git",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
atom-color-highlight, v3.0.8
atom-justify, v0.4.1
autocomplete-atom-api, v0.5.0
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-plus, v2.2.0
coffee-compile, v0.11.0
color-picker, v1.4.4
column-select, v0.1.0
compare-files, v0.4.1
emmet, v2.3.4
file-icons, v1.5.0
highlight-selected, v0.9.1
language-coffee-script-angular, v2.2.0
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-pylint, v0.2.1
linter-xmllint, v0.0.5
minimap, v4.3.1
minimap-find-and-replace, v4.1.0
open-recent, v2.2.0
rulerz, v0.2.2
status-bar, v0.63.0
Sublime-Style-Column-Selection, v1.2.3
symbols-tree-view, v0.6.1
tree-view-open-files, v0.2.3

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report. Can you try updating to the latest version (0.186.0) and see if you can reproduce this in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by papermoon1978** [comment]
No I cannot. Unfortunately. The 186 didn't show up as update in the menu. So I removed atom completely, but cannot install 186 because of an Squirrel error during the setup. :-(

**Comment by izuzak** [comment]
Can you share the full error you got during setup?

**Comment by papermoon1978** [comment]
Sure, but if you want I can also post this somewhere else ...

![atomsetup 1 exe_2015-03-06_14-34-47](https://cloud.githubusercontent.com/assets/4062007/6526086/0e5332cc-c40e-11e4-98df-108b6fb64ae5.png)


Log mentioned:

Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\andre lerche\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\andre lerche\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\andre lerche\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\andre lerche\AppData\Local\atom\app-0.176.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\andre lerche\AppData\Local\atom\app-0.176.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.176.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.176.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\andre lerche\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\andre lerche\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\andre lerche\AppData\Local\atom\app-0.186.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\andre lerche\AppData\Local\atom\app-0.186.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\andre lerche\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\andre lerche\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\andre lerche\AppData\Local\atom\app-0.186.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\andre lerche\AppData\Local\atom\app-0.186.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\andre lerche\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\andre lerche\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\andre lerche\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\andre lerche\AppData\Local\atom\app-0.186.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ed.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()

**Comment by izuzak** [comment]
Thanks! It seems that there's a few open and closed issues with the same error message. Can you try some of the approaches recommended in those issues and see if they help?

https://github.com/atom/atom/issues?q=is%3Aissue+Failed+to+update+local+releases+file%3A+System.IO.IOException%3A+The+file+exists.

**Comment by papermoon1978** [comment]
Yes you are right. For me cleaning up AppData/local/temp also solved the issue. Also the status bar issue doesn't happen in 186. So both are solved :-)

**Comment by izuzak** [comment]
High-5, thanks for taking the time to follow this through! Closing this out then. :sunglasses:
