### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by clementi** [atom/status-bar#85]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v0.74.0

### Stack Trace

Failed to activate the linter package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  at Error (native)
  at status-bar.StatusBarView.addLeftTile (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\status-bar\lib\status-bar-view.js:74:22)
  at LinterViews.attachBottom (C:\Users\Jeff\.atom\packages\linter\lib\linter-views.coffee:112:34)
  at Object.module.exports.consumeStatusBar (C:\Users\Jeff\.atom\packages\linter\lib\main.coffee:43:21)
  at Provider.module.exports.Provider.provide (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:34)
  at ServiceHub.module.exports.ServiceHub.consume (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:48:18)
  at Package.module.exports.Package.activateServices (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:380:69)
  at Package.module.exports.Package.activateNow (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:243:16)
  at C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.activate (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
  at C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:306:60
  at exit (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\Jeff\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -1:50.3.0 settings-view:view-installed-packages (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-jinja2, v0.5.0
atom-yeoman, v0.3.11
language-bison, v1.0.0
language-csharp, v0.6.0
language-dart, v0.2.0
language-fsharp, v0.8.4
language-haskell, v1.1.5
language-ocaml, v1.1.1
language-prolog, v0.10.0
language-scala, v1.1.3
linter, v1.0.6

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Having a look now. Thanks for reporting.

**Comment by k2b6s9j** [comment]
Hmm... What are your linter settings? Is this a fresh install?

**Comment by lierdakil** [comment]
Might that be some weird package conflict? What is that `.bin, vundefined` package in package list?

@clementi, could you disable all other user packages except linter and try again?

**Comment by 50Wliu** [comment]
No response, closing.
